server:
  port: 8089
  address: 0.0.0.0
spring:
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 100MB
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://47.97.231.180:3310/vaccine?characterEncoding=utf-8&useSSL=false
    username: root
    password: root
  jdbc:
      template:
        query-timeout: 3
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl